ALTER TABLE portfolios
ALTER COLUMN specialization TYPE VARCHAR(50);

ALTER TABLE portfolios
ADD CONSTRAINT chk_specialization CHECK (specialization IN (
    'JAVA_DEVELOPER',
    'PYTHON_DEVELOPER',
    'JAVASCRIPT_DEVELOPER',
    'TYPESCRIPT_DEVELOPER',
    'GO_DEVELOPER',
    'RUST_DEVELOPER',
    'CSHARP_DEVELOPER',
    'CPP_DEVELOPER',
    'FRONTEND_DEVELOPER',
    'BACKEND_DEVELOPER',
    'FULLSTACK_DEVELOPER',
    'DEVOPS_DEVELOPER',
    'DATA_ENGINEER',
    'DATA_SCIENTIST',
    'ML_ENGINEER',
    'MOBILE_DEVELOPER',
    'QA_ENGINEER',
    'SECURITY_ENGINEER',
    'UI_UX_DESIGNER',
    'PRODUCT_MANAGER',
    'OTHER'
));